defaults:
  - _self_
  - optimizer: adam
  - module: base

_target_: training.trainer.Trainer
_partial_: True

num_pseudo_epochs: 80
steps_per_epoch: 1000
validation_frequency_epochs: 5
ckpt_frequency_epochs: 10
#train_table: datasets/riemann_invariants/riemann_invariants_only_train_filtered.csv
#val_table: datasets/riemann_invariants/riemann_invariants_only_val.csv
train_table: datasets/riemann_invariants_with_true_targets/all_filtered_part1.csv
val_table: datasets/riemann_invariants_with_true_targets/all_filtered_part2.csv
batch_size: 32
feature_cols: 14
target_cols: 2

optimizer:
  _partial_: True

